// <auto-generated />
using System;
using KYC.TrueFace.Core.Infra.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KYC.TrueFace.Core.Infra.Data.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902233303_AddLoginLockout")]
    partial class AddLoginLockout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.Onboarding", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodePartner")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InclusionDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PathDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathSelfie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Situation")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SituationDt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.HasIndex("CodePartner");

                    b.ToTable("Onboardings");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.OnboardingResult", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeOnboarding")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InclusionDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("CodeOnboarding");

                    b.ToTable("OnboardingsResults");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InclusionDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Situation")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.PartnerCredentials", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CodePartner")
                        .HasColumnType("uuid");

                    b.Property<string>("GrantType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InclusionDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Situation")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("CodePartner");

                    b.ToTable("PartnersCredentials");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CodePartner")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InclusionDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotherName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<int>("Situation")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("CodePartner");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.UserAccess", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InclusionDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetPasswordTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResetPasswordTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Situation")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UsersAccess");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.UserAccessLog", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeUserAccess")
                        .HasColumnType("uuid");

                    b.Property<int>("Flow")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InclusionDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SituationDt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.HasIndex("CodeUserAccess");

                    b.ToTable("UsersAccessLogs");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.Onboarding", b =>
                {
                    b.HasOne("KYC.TrueFace.Core.Domain.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("CodePartner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.OnboardingResult", b =>
                {
                    b.HasOne("KYC.TrueFace.Core.Domain.Entities.Onboarding", "Onboarding")
                        .WithMany()
                        .HasForeignKey("CodeOnboarding")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onboarding");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.PartnerCredentials", b =>
                {
                    b.HasOne("KYC.TrueFace.Core.Domain.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("CodePartner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.User", b =>
                {
                    b.HasOne("KYC.TrueFace.Core.Domain.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("CodePartner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("KYC.TrueFace.Core.Domain.Entities.UserAccessLog", b =>
                {
                    b.HasOne("KYC.TrueFace.Core.Domain.Entities.UserAccess", "UserAccess")
                        .WithMany()
                        .HasForeignKey("CodeUserAccess")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
