export function Button(props) {
  return(
    <div className="
      flex
      justify-center
      w-full
    ">
      <button type="submit" className="
        bg-primary
        text-btn-login
        text-shadow-xs 
        flex
        items-center
        justify-center
        border-btn-login
        font-semibold
        py-2
        px-4
        w-full
        cursor-pointer
        rounded-full 
        h-10 
        overflow-hidden 
        focus:brightness-110 
        transition-all 
        disabled:cursor-not-allowed 
        disabled:opacity-10 
        disabled:grayscale 
        disabled:translate-y-0 
        disabled:hover:translate-y-0 
        hover:scale-90
        min-w-full 
        border-2! 
        border-brand-primary! 
        transparent
        "
      onClick={props.handlerAction}
      >
        {props.title}
      </button>
    </div>
  )
}